name: Docker Deploy Action

description: >
  🪂  A Github Action to deploy pages

branding:
  icon: 'command'
  color: 'yellow'

inputs:
  docker_hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}
    required: false
  docker_hub_password:
    description: Docker Hub password
    required: true
  docker_hub_token:
    description: Docker Hub authentication token
    required: true
  initiate_pauli_sum:
    description: Build args
    required: false
    default: ""
  image_name:
    description: Tag to use for the new image
    default: ${{ github.action_repository }}
    required: true
  credentials:
    description: The Google cloud credentials
    required: true
  token:
    description: The Github personal token
    required: true
  pypi_token:
    description: The monitor token
    required: true
  bot_token:
    description: The monitor token
    required: true
  logs_token:
    description: The warning token
    required: true
  chat_id:
    description: The telegram chat id
    required: true
  api_key:
    description: The key of api application
    required: true
  api_secret:
    description: The secret of api application
    required: true

outputs:
  addition:
    description: Collect addition outputs
    value: ${{ inputs.id == 1 && steps.addition.outputs.artifact }}
  multiplication:
    description: Collect multiplication outputs
    value: ${{ toJSON(steps.multiplication.outputs) }}

runs:
  using: composite
  steps:
    - name: Target Configuration
      uses: eq19/eq19/.github/actions/1-addition/2-feed@v2
      if: ${{ env.JOBS_ID == 1 }}
      id: addition
      with:
        hub_username: ${{ inputs.docker_hub_username }}
        hub_password: ${{ inputs.docker_hub_password }}
        hub_token: ${{ inputs.docker_hub_token }}
        credentials: ${{ inputs.credentials }}
        action_path: ${{ github.action_path }}
        image_name: ${{ inputs.image_name }}
        api_secret: ${{ inputs.api_secret }}
        api_key: ${{ inputs.api_key }}
        chat_id: ${{ inputs.chat_id }}
        pypi_token: ${{ inputs.pypi_token }}
        logs_token: ${{ inputs.logs_token }}
        bot_token: ${{ inputs.bot_token }}
        token: ${{ inputs.token }}

    - name: Profiling Feedback
      uses: eq19/eq19/.github/actions/2-multiplication/2-feed@v2
      if: ${{ env.JOBS_ID == 2 }}
      id: multiplication
      with:
        token: ${{ inputs.token }}
        chat_id: ${{ inputs.chat_id }}
        bot_token: ${{ inputs.bot_token }}
        logs_token: ${{ inputs.logs_token }}
        image_name: ${{ inputs.image_name }}
        action_path: ${{ github.action_path }}
        hub_token: ${{ inputs.docker_hub_token }} 
        hub_username: ${{ inputs.docker_hub_username }}
