name: Cancel & Rerun Workflow

on:
  workflow_dispatch:

jobs:
  cancel-and-rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest run ID
        id: get_run
        run: |
          run_id=$(gh run list -w "main.yml" -L 1 --json databaseId -q '.[0].databaseId')
          echo "RUN_ID=$run_id" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Cancel it
        run: gh run cancel "$RUN_ID"
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Re-run it
        run: gh workflow run main.yml --ref main
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
